server {
    listen {
         {
            .interface
        }
        }: {
             {
                .port
            }
            } default_server;

            default_server;
            : {
                 {